##
# After cloning, run `mise trust` then `mise install`
# to install these tools in this repository.
#
# To use Mise in a pipeline or Bash script, add this
# somewhere in the script before calling a Mise command:
#   eval "$(/usr/local/bin/mise activate bash)"
#
# For Powershell, do:
#   mise activate pwsh | Invoke-Expression
##

[tools]
## https://mise-tools.jdx.dev/tools/python
python = "3.13"
## https://mise-tools.jdx.dev/tools/pipx
"aqua:pypa/pipx" = "latest"

## https://github.com/aquaproj/aqua-registry/blob/main/pkgs/go-task/task/pkg.yaml
"aqua:go-task/task" = "latest"

## https://mise-tools.jdx.dev/tools/yamllint
yamllint = "latest"
